server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/twitterdb
    username: root
    password: fatih0001

flyway:
  url: jdbc:mysql://localhost:3306/twitterdb
  schemas: twitterdb
  user: root
  password: fatih0001

twitterclone:
  cloud:
    redis:
      host: localhost
      port: 7001
  pusher:
    appId: 1275062
    key: a42cb9c7c355c51291ea
    secret: 5b57edf9ab56aac383a0
    cluster: ap1

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            security: WARN